version: "3.1"
services:
 crypto-db:
    image: postgres:12
    restart: always
    container_name: crypto-db
    tty: true
    volumes:
      - /var/lib/pg_crypto_docker/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=crypto_db
    ports:
      - "5433:5432"
    networks:
      crypto:
 mongo:
    container_name: crypto-mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27017
    networks:
      crypto:
 mongo-express:
    container_name: crypto-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: crypto-mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      crypto:
networks:
  crypto:
    driver: bridge